name:                haskells-game-of-life
version:             0.1.0.0
github:              "mikenomitch/haskells-game-of-life"
author:              "Mike Nomitch"
maintainer:          "mikenomitch@gmail.com"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/mikenomitch/haskells-game-of-life#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: app

executables:
  haskells-game-of-life-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskells-game-of-life
